---
title: Tables in the project
mainfont: Arial
fontsize: 11pt
geometry: margin=0.8in
author:  
output: 
  pdf_document: 
    keep_tex: true
    number_sections: true
    latex_engine: xelatex
    # includes:  
    #   in_header: preamble-latex.tex
classoption: a4paper
---


# Multilevel 2by2 table 1
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/CW2CB2results.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c("Variables", "Latent class = 1", "Latent class = 2", "P value [note]")

dt[28, 1] <- c("Hypertension (%) [note]")
dt[32, 1] <- c("Carbohydrate\npercent (%) [note]")
dt[35, 1] <- c("DM [note]")
dt[36, 1] <- c("Physical\nactivity (hours/day) [note]")


kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Means, percentages, and 95 percent CIs of the characteristics by latent class memberships in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", 
      booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(3:6, 9, 10, 12:19, 23:25, 27, 29)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey", 
                       "rolling programme; BMI body mass index; WC, waist circumference; A1C, haemoglobin A1c;", 
                       "DM, diabetes mellitus.", 
                       "Variables from the blood tests (glucose and A1C) are weighted by blood sample weights,", 
                       "the others are weighted by individual weights.", 
                       "Glucose and A1C levels are estimated in subgroups of people without diabetes.")) %>% 
  add_footnote(c("For continuous variables, the F test was used to determine differences between latent classes. For categorical variables, differences between latent classes were assessed using the adjusted Pearson Chi-2 test for survey data.",
                 "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.", 
                 "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 "DM was defined by A1C > 6.5%.", 
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity during the survey."), 
               notation = "symbol")
```

# Day level only models
```{r echo=FALSE, message=FALSE, warning=FALSE}
# library(kableExtra)
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/ndns_level1only.csv", header = T)
names(dt) <- c("N of classes", "N of free parameters","log-likelihood",  "AIC", "BIC", "aBIC", "Entropy", "Lo-Mendel-Rubin LRT")
dt[1,8] <- "--"
dt[2,8] <- "< 0.0001"
dt[3,8] <- "< 0.0001"
kable(dt, digits = 3, row.names = FALSE, align = "c",
              format = "latex", caption = "Level 1 class selection. (All data, n = 6155, 24483 data points)", 
      booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
# row_spec(c(2,3), bold = T, color = "white", background = "#D7261E") %>% 
  footnote(general = c("Abbreviation: N, number; AIC, Akaike information criterion; BIC, Bayesian information criterion; aBIC, adjusted BIC;" ,
                       "Entropy, a pseudo-r-squared index; Lo-Mendel-Rubin LRT, likelihood ratio test comparing q classes models with", 
                       "q-1 classes models."))
```


# LCGA models table 1
```{r echo=FALSE, message=FALSE, warning=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/LCGA3Cresults.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c("Variables", "Latent class = 1", "Latent class = 2", "Latent class = 3", "P value [note]")


dt[28, 1] <- c("Hypertension (%) [note]")
dt[32, 1] <- c("Carbohydrate\npercent (%) [note]")
dt[35, 1] <- c("DM [note]")
dt[36, 1] <- c("Physical\nactivity (hours/day) [note]")


kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Means, percentages, and 95 percent CIs of the characteristics by latent class memberships in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", 
      booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(3:6, 9, 10, 12:19, 23:25, 27, 29)) %>% 
   footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey", 
                       "rolling programme; BMI body mass index; WC, waist circumference; A1C, haemoglobin A1c;", 
                       "DM, diabetes mellitus.", 
                       "Variables from the blood tests (glucose and A1C) are weighted by blood sample weights,", 
                       "the others are weighted by individual weights.", 
                       "Glucose and A1C levels are estimated in subgroups of people without diabetes.")) %>% 
  add_footnote(c("For continuous variables, the F test was used to determine differences between latent classes with Bonferroni correction to account for multiple testing across >2 classes. For categorical variables, differences between latent classes were assessed using the adjusted Pearson Chi-2 test for survey data.",
                 "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.", 
                 "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 "DM was defined by A1C > 6.5%.", 
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity during the survey."), 
               notation = "symbol")
```





# Model fit criteria
```{r echo=FALSE, message=FALSE, warning=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/Mixed_7slots.csv", header = T)
dt <- dt[,-7]
names(dt) <- c("Model", "1 class", "2 classes",  "3 classes", "4 classes", "5 classes")
dt[is.na(dt)] <- ""
# library(formattable)

kable(dt, digits = 3, row.names = FALSE, align = "c",
      format = "latex", caption = "Fit Criteria for Each Model Specification", 
      booktabs = T, linesep = "") %>% 
  kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_header_above(c(" ", "Number of level 1 classes" = 5)) %>% 
  group_rows("Fixed effects model", 1, 5) %>%
  group_rows("Random effects model", 6, 20) %>%
  add_indent(c(2:5,7:10,12:15,17:20)) %>% 
  footnote(general = c("Abbreviation: No, number; BIC, Bayesian information criterion; Entropy, a pseudo-r-squared index; Lo-Mendel-Rubin LRT, likelihood ratio test comparing q classes models with q-1 classes models."))

```


# Day level solution 1
```{r echo=FALSE, message=FALSE, warning=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/timeslots_cw3cb3_univariate.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c("Time slots of the day", "Responses of carbohydrate intake", "Frequency", "Precentages (%)", 
               "Class 1 (30.8%)", "Class 2 (39.8%)", "Class 3 (29.5%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Day Level Latent Class Solution for Three-Class Model (No Individual level Model)", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
    add_header_above(c(" ", " ", " ", " ", "High carbohydrate day", "Lower carbohydrate day", "Regular day"))

```

# Day level solution characteristics

```{r echo=FALSE, message=FALSE, warning=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/Daylevel.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c(" ", "High carbohydrate day", "Low carbohydrate day", "Regular meals day", "P value[note]")



dt[23, 1] <- c("Non-milk extrinsic sugar[note]")
# dt[32, 1] <- c("Carbohydrate\npercent (%) [note]")
# dt[35, 1] <- c("DM [note]")
# dt[36, 1] <- c("Physical\nactivity (hours/day) [note]")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Means (sd), and counts  of the characteristics of different types of days according to carbohydrate intake.", booktabs = T,linesep = "") %>%
    add_indent(c(3:6, 8:15)) %>% 
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_footnote(c("P values were obtained from chi-square test for categorical variables, and one-way ANOVA comparing the means in multiple groups for continuous variables;", 
                       "Non-milk extrinsic sugar is defined as:"),  notation = "symbol")

```





# Social economic 

```{r tab1, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/Timeslots_CW3CB3results.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c("Variables", "Individual class 1 (n = 1730)", "Individual class = 2 (n = 1772)", "Individual class = 3 (n = 2653)", "P value [note]")

# 
# dt[28, 1] <- c("Hypertension (%) [note]")
# dt[32, 1] <- c("Carbohydrate\npercent (%) [note]")
# dt[35, 1] <- c("DM [note]")
# dt[36, 1] <- c("Physical\nactivity (hours/day) [note]")
dt[20, 1] <- c("Paid employment[note] (%)")
dt[23, 1] <- c("Live with partner[note] (%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Means, row percentages, and 95 CIs of the characteristics by latent class memberships in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(3:6, 9, 10, 12:19, 21, 22, 24, 25, 28, 29, 31, 32)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey rolling programme;"
                       # " BMI body mass index; WC, waist circumference; A1C, haemoglobin A1c; DM, diabetes mellitus.", 
                       # "Variables from the blood tests (glucose and A1C) are weighted by blood sample weights, the others are weighted by individual weights.", 
                       # "Glucose and A1C levels are estimated in subgroups of people without diabetes."
                       )) %>% 
  add_footnote(c("For continuous variables, the F test was used to determine differences between latent classes with Bonferroni correction to account for multiple testing across >2 classes. For categorical variables, differences between latent classes were assessed using the adjusted Pearson Chi-2 test for survey data.",
                 "Paid employment was defined as being in paid employment during the last 4 weeks prior to the survey." , 
                 "Live with partner was defined as either living with a married husband/wife or a legally recognised civil partnership."
                 # "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.", 
                 # "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 # "DM was defined by A1C > 6.5%.", 
                 # "Physical activity was calculated as mean time spent at moderate or vigorous physical activity during the survey."
                 ), 
               notation = "symbol")
```



## Anthropometric measurements and biochemical analysis


```{r tab2, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/Timeslots_CW3CB3table2_bmiDM.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c("Variables", "Individual class 1 (n = 1730)", "Individual class (n = 1772)", "Individual class 3 (n = 2653)", "P value[note]")

# 
dt[9, 1] <- c("Hypertension[note] (%)")
dt[13, 1] <- c("Carbohydrate percent[note] (%)")

dt[21, 1] <- c("Physical\nactivity (hours/day) [note]")
dt[20, 1] <- c("DM [note]")
# dt[20, 1] <- c("Paid employment[note] (%)")
# dt[23, 1] <- c("Live with partner[note] (%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Means, percentages, and 95 CIs of the characteristics by latent class memberships in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(4:6,8,10)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey rolling programme;",
                        " BMI body mass index; WC, waist circumference; A1C, haemoglobin A1c; DM, diabetes mellitus.", 
                        "Variables from the blood tests (glucose and A1C) are weighted by blood sample weights, the others are weighted by individual weights.", 
                        "Glucose and A1C levels are estimated in subgroups of people without diabetes.")) %>% 
  add_footnote(c("For continuous variables, the F test was used to determine differences between latent classes with Bonferroni correction to account for multiple testing across >2 classes. For categorical variables, differences between latent classes were assessed using the adjusted Pearson Chi-2 test for survey data.",
                 # "Paid employment was defined as being in paid employment during the last 4 weeks prior to the survey." , 
                 # "Live with partner was defined as either living with a married husband/wife or a legally recognised civil partnership."
                 "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.",
                 "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 "DM was defined by A1C > 6.5%.",
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity including both work-related and recreational activities during the survey."
                 ), 
               notation = "symbol")
```


## Hypertension table 1



```{r tab1hypetension, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/hypertensiontab1.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c(" ", "Non-hypertensive", "Hypertensive", "P value[note]", 
               "Non-hypertensive", "Hypertensive", "P value")

# 
# dt[9, 1] <- c("Hypertension[note] (%)")
# dt[13, 1] <- c("Carbohydrate percent[note] (%)")

dt[17, 1] <- c("Physical\nactivity (hours/day) [note]")
# dt[20, 1] <- c("DM [note]")
# dt[20, 1] <- c("Paid employment[note] (%)")
# dt[23, 1] <- c("Live with partner[note] (%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Weighted means, percentages, and 95 CIs of the characteristics by hypertension status in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(3:6,8,9,11,12,14,15,16,21:23)) %>% 
   add_header_above(c(" ", "Men (n = 2537)" = 3, "Women (n = 3618)" = 3)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey rolling programme;",
                        " BMI body mass index; WC, waist circumference.", 
                        "Variables are weighted by nurse visiting weights.")) %>% 
  add_footnote(c("Significant sex-specific differences by hypertension status assessed using an F test for continuous variables or design-adjusted Pearson chi-square test",
                 # "Paid employment was defined as being in paid employment during the last 4 weeks prior to the survey." , 
                 # # "Live with partner was defined as either living with a married husband/wife or a legally recognised civil partnership."
                 # "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.",
                 # "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 # "DM was defined by A1C > 6.5%.",
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity including both work-related and recreational activities during the survey."
                 ), 
               notation = "symbol")
```



## BMI 

```{r tab1BMI, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/BMItab1.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c(" ", "Normal weight", "Overweight", "Obese", "P value[note]", "Normal weight", "Overweight", "Obese", "P value")

# 
# dt[9, 1] <- c("Hypertension[note] (%)")
# dt[13, 1] <- c("Carbohydrate percent[note] (%)")

dt[17, 1] <- c("Physical\nactivity (hours/day) [note]")
# dt[20, 1] <- c("DM [note]")
# dt[20, 1] <- c("Paid employment[note] (%)")
# dt[23, 1] <- c("Live with partner[note] (%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Weighted means, percentages, and 95 CIs of the characteristics by hypertension status in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(6:9, 11,12, 14,15, 17:19, 22:24)) %>% 
   add_header_above(c(" ", "Men (n = 2537)" = 4, "Women (n = 3618)" = 4)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey rolling programme;",  
                       " BMI body mass index; WC, waist circumference.", 
                       "Variables are weighted by nurse visiting weights.")) %>% 
  add_footnote(c("Significant sex-specific differences by BMI categories assessed using an F test (with Bonferroni correction to account for multiple testing across $>$ 2 groups) for continuous variables or design-adjusted Pearson chi-square test",
                 # "Paid employment was defined as being in paid employment during the last 4 weeks prior to the survey." , 
                 # # "Live with partner was defined as either living with a married husband/wife or a legally recognised civil partnership."
                 # "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.",
                 # "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 # "DM was defined by A1C > 6.5%.",
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity including both work-related and recreational activities during the survey."
                 ), 
               notation = "symbol")
```


## DM 


```{r tab1BMI, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dt <- read.csv("/home/wangcc-me/Documents/LSHTMproject/Tablecsv/BMItab1.csv", header = T, row.names = NULL, colClasses = "character")
names(dt) <- c(" ", "Normal weight", "Overweight", "Obese", "P value[note]", "Normal weight", "Overweight", "Obese", "P value")

# 
# dt[9, 1] <- c("Hypertension[note] (%)")
# dt[13, 1] <- c("Carbohydrate percent[note] (%)")

dt[17, 1] <- c("Physical\nactivity (hours/day) [note]")
# dt[20, 1] <- c("DM [note]")
# dt[20, 1] <- c("Paid employment[note] (%)")
# dt[23, 1] <- c("Live with partner[note] (%)")

kable(dt,  align = "l", row.names = FALSE,
              format = "latex", caption = "Weighted means, percentages, and 95 CIs of the characteristics by hypertension status in the UK adults (NDNS RP 2008/09-2015/16, sample size = 6155).", booktabs = T,linesep = "") %>%
 kable_styling(latex_options = c("striped"), font_size = 9) %>% 
  add_indent(c(6:9, 11,12, 14,15, 17:19, 22:24)) %>% 
   add_header_above(c(" ", "Men (n = 2537)" = 4, "Women (n = 3618)" = 4)) %>% 
  footnote(general = c("Abbreviations: CI, confidence intervals; NDNS RP, national dietary and nutrition survey rolling programme;",  
                       " BMI body mass index; WC, waist circumference.", 
                       "Variables are weighted by nurse visiting weights.")) %>% 
  add_footnote(c("Significant sex-specific differences by BMI categories assessed using an F test (with Bonferroni correction to account for multiple testing across $>$ 2 groups) for continuous variables or design-adjusted Pearson chi-square test",
                 # "Paid employment was defined as being in paid employment during the last 4 weeks prior to the survey." , 
                 # # "Live with partner was defined as either living with a married husband/wife or a legally recognised civil partnership."
                 # "Hypertension was defined as either systolic blood pressure >= 140 mmHg or diastolic blood pressure >= 90 mmHg, or under treatment for hypertension.",
                 # "Carbohydrate percent indicates the percentage of energy from carbohydrate in total energy intake",
                 # "DM was defined by A1C > 6.5%.",
                 "Physical activity was calculated as mean time spent at moderate or vigorous physical activity including both work-related and recreational activities during the survey."
                 ), 
               notation = "symbol")
```
