---
title: "Memo of meeting"
output: word_document
---


**Date and time:** 2018-06-25 14:00 - 15:00

**Attendees:** Professor Luigi Palla, Dr. Suzana Almoosawi, Chaochen Wang

**Notekeeper:** Chaochen Wang

**Main Topic:** how to define an eating occasion specifically for carbohydrate intake or what approaches can we use to analysis the eating time pattern of carbohydrate. 

- From Professor Luigi: 
    - We may use gram consumed per hour; 
    - Percentage of energy from carbohydrate per eating occasion (we already know that the cut-off value for energy eating occasion is defined as $\geqslant$ 210 kJ); 
    - Or is there any definition of eating time window block? (For total energy intake we used 15 minutes).
    
- From Dr. Suzana: 
    - According to the guideline (which?), it is suggested that the distribution of carbohydrate intake should be equal for breakfast (25%), lunch (25%), dinner (25%), and snacks (25%). Therefore, the recommendation is 270 g/day (for both men and women?) which lead to 67.5 gram per meal.
    - Or if we consider the composition of energy sources, it is also recommended that 25% of the total energy should come from carbohydrates.
    - We may also use the ratio of carbohydrates and (for example) fibre: 1 g fibre/ 10 g carbohydrates.
    - In the NDNS survey, they already defined 7 meal blocks: 
        - breakfast (6 am to 9 am); 
        - mid-morning snack (9 am to 12 noon); 
        - lunch (12 noon to 2 pm); 
        - afternoon snack (2 pm to 5 pm); 
        - dinner (5 pm to 8 pm); 
        - late-night snack (8 pm to 10 pm); 
        - midnight snack (10 pm to 6 am).
    - Use the already defined 7 meal blocks will be easier in terms of comparing with existing publications from NDNS data.
    
- From Professor Luigi: 
    - Can we use 1 hour window for each participant? So each person will have 24 time sequence of eating (carbohydrates) per day. 
    - **We may calculate the energy consumption per hour for each participant. And also calculate the percentage of energy that come from carbohydrate each hour. Would that be sensible?**
    - What cut-off would be appropriate to say that within that specific hour, the consumption of carbohydrates would be good or bad?
    - **Just to add that if there is a concern that too few people would have consumed CH for example at night then we can collapse the hours at night into one class as we did with Raoul, say from 11pm till 5am or from 12 till 6am.**
    
- From Dr. Suzana: 
    - Probably, this could be an option. Usually, a food product/meal can be categorised as with low carbohydrates or sugar condensed if the contribution of energy from carbohydrates in that food/meal is lower than 25% or higher than 70%: 
        - if 25% energy from carbohydrates $\Rightarrow$ low-carbohydrates; 
        - if 70% energy from carbohydrates $\Rightarrow$ high-carbohydrates; 
        - if 26% ~ 69% energy from carbohydrates $\Rightarrow$ medium-carbohydrates.
    - But if we need to dichotomise, I need to confirm again whether there is any evidence/suggestion about that.
    - Still, this could the first step of our analysis. The second step we may think about is the quality (ratio) between different subtypes of carbohydrates within the hour. 
    


----------


**Date and time:** 2018-07-10 14:00 - 15:00

**Attendees:** Professor Luigi Palla, Dr. Suzana Almoosawi, Chaochen Wang

**Notekeeper:** Chaochen Wang

**Main Topic:** Discuss about the preliminary results and what should we do next?         
        
- From what we have seen from the preliminary results, maybe we should change the cut-off values to 25%, 50%, and 75% (i.e. four categories), in order to divide the previous 26% to 75% category (medium carbohydrate food/meal). 

- After the above step, maybe we can further consider combining the lower two categories (< 25% and 26% to 50%) and the higher two categories (50% to 75% and > 75%). 

- One possibility of next analysis objective could be:  carb-fibre ratio and various variation of this ratio. Usually I (Dr. Suzana) would calculate how much fibre is provided for every 10g of carbohydrate for each food product. For example, a product providing 30g of carb and 15g of fibre would have a carb-fibre ratio of 10:5. It may be the case that the same rules applies to eating occasions/meals. In the past I (Dr. Suzana) usually used to calculate the ratio and then use the actual proportion within the analysis, so a fibre-carb ratio of 2-10 would expressed as 0.2, and 1-10 would be 0.1. I wonder if given that the carb value remain always constant at 10g whether we could simply use the value for the fibre 2, 1...etc

- Comment SA: Reviewing the work of Morimoto and Ghodsian, Morimoto calculated a fibre-to-carb ratio by dividing fibre in grams by carbohydrates in grams multiplied by 100%. Taken the example above, this will be 15/30*100 = 50.
Ghodsian calculated the carb:fibre ratio by diving carbohyrdrates in grams by fibre in grams.  Although these methods are currently used in the literature, **standardizing everything by 10g of carbohydrates makes the findings easier to interpret in terms of public health.** For example, a person can see that a food product with a minimum of 1g of fibre per 10g of crabohydrates is a good quality carbohydrate product, whereas if the fibre value falls below 1 then it means it is of poorer carbohydrate quality.

(Morimoto, N., Kasuga, C., Tanaka, A., Kamachi, K., Ai, M., Urayama, K., & Tanaka, A. (2018). Association between dietary fibre:carbohydrate intake ratio and insulin resistance in Japanese adults without type 2 diabetes. British Journal of Nutrition,119(6), 620-628. doi:10.1017/S0007114517003725)

(Ghodsian B1, Madden AM1.Evaluating the ≤10:1 wholegrain criterion in identifying nutrient quality and health implications of UK breads and breakfast cereals. Public Health Nutr. 2018 Apr;21(6):1186-1193. doi: 10.1017/S1368980017003718. Epub 2017 Dec 26.)

- How to use our results from mixed LCA analysis to express the variability or regularity of carbohydrate eating within a person? 

(The following idea is from Chaochen Wang, not fully discussed yet.)

- After we can decide the number of classes in the study sample, maybe we can create a variable according to their change of classes during the survey. 
    - For example, if we decided to use 3 classes or maybe 4 classes. We can use the personal class change as a way to express the regularity. 
        - In this case, if for four days survey, the subject stayed in the same class, he/she can be considered as a regular eater. 
        - For the others, if they change class for more than 1 day, he/she can be considered as a irregular eater.
        - So in the sample we will separate the subjects into regular eaters or not (2 groups)
    - Another way, probably we can try to define them with less strict rules:
        - For more than half (2 in 2, 2 in 3, or >=2 in 4) survey days, if the subject managed to stay in the same class, then he/she can be defined as a regular eater.
        - Otherwise, he/she is defined as an irregular eater. 
    - The two approaches proposed here, one is more strict than the other is because there may be only small numbers of people actually stayed in the same class for all four survey days. Because with the number of latent classes increases, the probability of jumping from one class to the other will increase, in other words, the probability of staying in the same class for four days will become lower and lower. 
- Comment SA: I like both approaches as it simply gives a dichotomized variable.  It is true that a certain degree of change in clusters is expected between weekdays and weekends.  Hence, it is difficult to assume that if a person shifts clusters between weekdays and weekends that they are irregular eaters. Moreover, defining how much change is a bad change is tricky, hence why I would have perhaps in the future used some form of a coefficient of variation to define variability or irregularity of eating, potentially based on the variable ‘Best’. 

    
    
- Survey weighting variables.    
    - There are different weighting variables in the data set.
        - Wti_CY1234 for dietary data
        - Wtb_CY1234 if using blood data to calculate presence or absence of diabetes status
        - wti_Y56
        - wtb_Y56
        
----------


**Date and time:** 2018-10-25 9:00 - 11:00 (London Time) / 17:00 - 19:00 Tokyo Time

**Attendees:** Professor Luigi Palla, Chaochen Wang

**Notekeeper:** Chaochen Wang

**Main Topic:** Mainly about the content to include/exclude in the paper


1. We talked about the grants and conferences: 
    1. Conference: [Winter Conference 2018 for nutrition](https://www.nutritionsociety.org/events/winter-conference-2018-optimal-diet-and-lifestyle-strategies-management-cardio-metabolic-risk) - No response yet. 
    2. Conference: [CHRONONUTRITION: FROM EPIDEMIOLOGY TO MOLECULAR MECHANISM SYMPOSIUM - LONDON](https://www.bna.org.uk/mediacentre/events/chrononutrition-from-epidemiology-to-molecular-mechanism-symposium-london/) - No response yet. 
    3. Probably both will need to prepare posters.
    4. Grants: Chao applied the JSPS-kakenhi (Japanese Government Grant), the result will be known after the New Year (probably around the end of March);
    4. Grants: Suzana applied the Daiwa grant, the result will probably be released before December. 

2. We talked where to submit the paper first - to the American Journal of Clinical Nutrition
    1. Chao will need to confirm about the requirements for authors. 
    2. tables decisions: 
        1. Table 3.1 (model fitting criteria) - go to supplementary
        2. Table 3.2 (day level model solution) - removed and use figure 3.1 instead.
        3. Table 3.3 (characteristics of day level classes) - go to supplementary
        4. Table 3.4 (individual level Carb eating composition by time slots) - stay in the main text
        5. Table 3.5-3.6 (social-demographic/biomedical measurement characteristics of individual level classes) - combined and stay in the main text
        6. Table 