---
title: "Some usefull words/expressions/sentences"
output: html_document
---


# Words

- discernable [di'sə:nəbl, -'zə:-]

```
===== 辞典翻译: discernable ======
adj. 可辨别的；可认识的
============ 网络释义 ============
-------- discernable ---------
可辨别的
方向
分辨
-- discernable recognizable --
可辨别的
--- discernable visible ----
可辨别的
```

-   abstinence ['æbstinəns]

```
====== 辞典翻译: abstinence ======
  n. 节制；节欲；戒酒；禁食
============ 网络释义 ============
--------- abstinence ---------
  节制
  禁欲
  禁戒
----- alcohol abstinence -----
  酒戒断
----- Abstinence theory ------
  节欲论
  弃权
  忍欲说
```

-  exhaustive [iɡ'zɔ:stiv]

```
====== 辞典翻译: exhaustive ======
  adj. 详尽的；彻底的；消耗的
============ 网络释义 ============
--------- Exhaustive ---------
  无遗
  详尽的
  全部
----- Exhaustive search ------
  穷举搜索
  穷举搜索完全搜索
  全程搜索
----- exhaustive voting ------
  淘汰投票
  消耗性投票
```

-   temperament ['tempərəmənt]

```
===== 辞典翻译: temperament ======
  n. 气质，性情，性格；急躁
============ 网络释义 ============
-------- temperament ---------
  气质
  气质 (心理学)
  性格
------ Well Temperament ------
  Well temperament
  Well Temperament
  平均律
---- Musical temperament -----
  律学
  一份音乐的气质
  音乐性
```

- trivial ['triviəl]

```
======= 辞典翻译: trivial ========
  adj. 不重要的，琐碎的；琐细的
============ 网络释义 ============
---------- trivial -----------
  琐碎的
  微不足道的
  小巫见大巫
------ Trivial Pursuit -------
  棋盘问答
  打破砂锅问到底
  追根究底
-------- trivial name --------
  惯用名
  俗名
  种名
```

- prudent ['pru:dənt]

```
======= 辞典翻译: prudent ========
  adj. 谨慎的；精明的；节俭的
  n. (Prudent)人名；(法)普吕当
============ 网络释义 ============
---------- prudent -----------
  谨慎的
  明智的
  审慎的
--------- prudent s ----------
  善于经营的
  谨慎
  精明的
----- PRESIDENT PRUDENT ------
  普鲁登特总统城
```

# Expressions



# Sentences

#### terry2017discontinuous - Discontinuous Patterns of Cigarette Smoking From Ages 18 to 50 in the United States: A Repeated-Measures Latent Class Analysis

- RMLCA models were fitted in SAS 9.4 using PROC LCA. Parameters were estimated by maximum likelihood using the EM algorithm.

- To ascertain if the same latent class structure was observed for males and females, multiple-group RMLCA models by sex were fitted in PROC LCA using the GROUPS statement (both with and without imposing measurement invariance across males and females).

- Model selection (ie, the number of latent classes specified) was determined by model fit, parsimony, and stability. 

- Simulations have shown that the Bayesian information criterion (BIC) and sample size-adjusted BIC (a-BIC) perform particularly well at selecting the “correct” latent class model.

- Improvement in both BIC and consistent Akaike information criterion (CAIC) values continued only through the 12-class model; thus, the 12-class model was selected as optimal.


#### lanza2007proc - PROC LCA: A SAS procedure for latent class analysis

- In traditional LCA, two sets of parameters are estimated: class membership probabilities and item-response probabilities conditional on class membership.

- Latent class models usually involve categorical indicators (although a version of LCA involving continuous indicators called latent profile analysis [Gibson, 1959] is being used increasingly).

- When categorical data are used, the latent class model has the advantage of making no assumptions about the distributions of the indicators other than that of local independence; that is, the assumption that within a latent class the indicators are independent.

- In PROC LCA, parameters are estimated by maximum likelihood using an EM (expectation-maximization) type procedure. Missing data on the latent class indicators are handled in this procedure, with data assumed to be missing at
random (MAR).

- A test of the null hypothesis that data are missing completely at random appears in the output.

- a helpful preliminary step in any LCA is exploring overall relations among pairs of items by conducting cross-tab analyses.


- A good starting point for identifying an optimal baseline model is to fit a sequence of models with two classes, three classes, and so on.

- A variety of tools can be used together for model selection, including the likelihood-ratio G 2 statis-
tic, Akaike’s Information Criterion (AIC; Akaike, 1974) and Bayesian Information Criterion (BIC; Schwarz, 1978).

- For example, each class should be distinguishable from the others on the basis of the item-response probabilities, no class should be trivial in size (i.e., with a near-zero probability of membership), and it should be possible to assign a meaningful label to each class.


- The AIC and BIC are penalized log-likelihood model information criteria that can be used to compare competing models (e.g., models with different numbers of latent classes) fit to the same data. A smaller AIC and BIC for a particular model suggests that the trade-off between fit and parsimony is preferable.

- Often when a grouping variable is included it is important to test for measurement invariance across groups. To do this, a model with free estimation of the $\rho$ parameters can be compared to the same model that includes restrictions equating the $\rho$ parameters across groups. A significant p value suggests that the null hypothesis of measurement invariance should be rejected.


- Based on a data set, a particular model specification, and starting values for the parameters, the algo-
rithm iterates between the Expectation (E) step and the Maximization (M) step until either the convergence criterion is achieved or the maximum number of iterations is reached.

- The best way to detect identification problems or local optima (i.e., solutions other than the optimal one) is to fit the same model using multiple sets of starting values. This can be done by calling the procedure repeatedly with different seeds specified.

- Even well-identified models can land on a different solution occasionally; if the solution with the smallest log-likelihood is arrived at using the majority of the seeds, one can have confidence that it is the optimal solution.
