---
title: "Preliminary results"
output: html_document
---


## Data description

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
setwd("~/Documents/LSHTMproject/Rcode")

load("LCA.Rdata")

library(epiDisplay)
library(plyr)
library(tidyverse)
library(poLCA)
# Number of subjects per survey year
with(NDNS, tab1(SurveyYear, graph = FALSE, decimal = 2))

# Number of subjects per servey year by gender where Men == 1, Women == 2

with(NDNS, tabpct(SurveyYear, Sex,  graph = FALSE, decimal = 2))


# summary of their age 

NDNS %>% 
  group_by(SurveyYear, Sex) %>% 
  summarise(N = n(), MeanAge = mean(Age), SDAge = sd(Age), minAge = min(Age), maxAge = max(Age))


# Dietary data by day

vecid1<-unique(dta_day1$id) # n = 6153
vecid2<-unique(dta_day2$id) # n = 6153
vecid3<-unique(dta_day3$id) # n = 6151
vecid4<-unique(dta_day4$id) # n = 6026

setdiff(vecid, vecid1) # two subjects did not have day 1 data

setdiff(vecid, vecid2) # two subjects did not have day 2 data

setdiff(vecid, vecid3) # four subjects did not have day 3 data

setdiff(vecid, vecid4) # 129 subjects did not have day 4 data
```




### day 1 data (3 classes)

```{r}


# LCA in day1 -------------------------------------------------------------

# noquote(paste(rep("H", 24), 0:23, sep = ""))
#H0  H1  H2  H3  H4  H5  H6  H7  H8  H9  H10 H11 H12 H13 H14 H15 H16 H17 H18 H19 H20 H21 H22 H23

f <- cbind(H0, H1, H2, H3, H4, H5, H6, H7, H8, H9, H10,H11,H12,H13,H14,H15,H16,H17,H18,H19,H20,H21,H22,H23) ~ 1
lc3 <- poLCA(f, dta_d1_wide, nclass = 3, graphs = TRUE, maxiter = 10000)


# lc3$llik #log-likelihood of model
# 
# lc3$P #Estimated class population shares 
# 
# lc3$predclass
```

### day 1 data (Fig.)

```{r echo=FALSE, fig.height=5, fig.width=14, message=FALSE, warning=FALSE}

library(ggthemr)
a <- (data.frame(lc3$probs))
a$Class <- c("Class1", "Class2", "Class3")

a_long <- a %>% 
  gather(Hour, Prob, -Class) %>% 
  separate(Hour, into = c("HourN", "Carbo"), sep = "\\.") 

a_long$HourN <- factor(a_long$HourN, levels = c("H0","H1" ,"H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23"))

a_long$Carbo <- factor(a_long$Carbo, levels = c("Low_carb", "Med_carb", "High_carb"))


a_long <- a_long %>% 
  filter(Carbo != "Not_eating")

ggthemr("fresh", layout = "scientific")

ggplot(a_long[a_long$Class == "Class1", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
  geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 1: 45.71%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class2", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 2:  41.71%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class3", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 3:  12.58%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))
```


### Model comparison and selection

```{r echo=FALSE}
library(kableExtra)
dt <- read.csv("../Tablecsv/Modelfitd01.csv", header = T)
names(dt) <- c("N of classes", "N of parameters", "G^2", "df", "AIC", "BIC", "log-likelihood")

kable(dt, digits = 3, row.names = FALSE, align = "c",
              format = "html", caption = "Model Comparison. (Day 1, n = 6153)") %>%
 kable_styling(font_size = 16, 
        bootstrap_options = c("striped", "hover", "condensed"),
        position = "center", full_width = FALSE) %>% 
  row_spec(5, bold = T, color = "white", background = "#D7261E") %>% 
  footnote(general = "Abbreviation: N, number; G^2, the likelihood ratio statistic; df, degree of freedom; AIC, Akaike information criterion; BIC, Bayesian information criterion.")
```

### Five classes visualisation


```{r echo=FALSE, fig.height=5, fig.width=14, message=FALSE, warning=FALSE}

library(ggthemr)

lc5 <- poLCA(f, dta_d1_wide, nclass = 5, graphs = FALSE, maxiter = 10000)


a <- (data.frame(lc5$probs))
a$Class <- c("Class1", "Class2", "Class3", "Class4", "Class5")

a_long <- a %>% 
  gather(Hour, Prob, -Class) %>% 
  separate(Hour, into = c("HourN", "Carbo"), sep = "\\.") 

a_long$HourN <- factor(a_long$HourN, levels = c("H0","H1" ,"H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23"))

a_long$Carbo <- factor(a_long$Carbo, levels = c("Low_carb", "Med_carb", "High_carb"))


a_long <- a_long %>% 
  filter(Carbo != "Not_eating")

ggthemr("fresh", layout = "scientific")

ggplot(a_long[a_long$Class == "Class1", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
  geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 1: 33.38%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class2", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 2:  25.89%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class3", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 3:  22.46%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))



ggplot(a_long[a_long$Class == "Class4", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 4:  7.65%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))


ggplot(a_long[a_long$Class == "Class5", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 5:  12.27%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))
```




### day 2 data (Fig.)

```{r echo=FALSE, fig.height=5, fig.width=14, message=FALSE, warning=FALSE}

library(ggthemr)
lc3 <- poLCA(f, dta_d2_wide, nclass = 3, graphs = FALSE, maxiter = 10000)


a <- (data.frame(lc3$probs))
a$Class <- c("Class1", "Class2", "Class3")

a_long <- a %>% 
  gather(Hour, Prob, -Class) %>% 
  separate(Hour, into = c("HourN", "Carbo"), sep = "\\.") 

a_long$HourN <- factor(a_long$HourN, levels = c("H0","H1" ,"H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23"))

a_long$Carbo <- factor(a_long$Carbo, levels = c("Low_carb", "Med_carb", "High_carb"))


a_long <- a_long %>% 
  filter(Carbo != "Not_eating")

ggthemr("fresh", layout = "scientific")

ggplot(a_long[a_long$Class == "Class1", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
  geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 1: 35.92%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class2", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 2:  12.50%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class3", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 3:  51.58%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))
```


### Model comparison and selection

```{r echo=FALSE}
library(kableExtra)
dt <- read.csv("../Tablecsv/Modelfitd02.csv", header = T)
names(dt) <- c("N of classes", "N of parameters", "G^2", "df", "AIC", "BIC", "log-likelihood")

kable(dt, digits = 3, row.names = FALSE, align = "c",
              format = "html", caption = "Model Comparison. (Day 2, n = 6153)") %>%
 kable_styling(font_size = 16, 
        bootstrap_options = c("striped", "hover", "condensed"),
        position = "center", full_width = FALSE) %>% 
  row_spec(5, bold = T, color = "white", background = "#D7261E") %>% 
  footnote(general = "Abbreviation: N, number; G^2, the likelihood ratio statistic; df, degree of freedom; AIC, Akaike information criterion; BIC, Bayesian information criterion.")
```

### Four classes visualisation


```{r echo=FALSE, fig.height=5, fig.width=14, message=FALSE, warning=FALSE}

library(ggthemr)

# lc4 <- poLCA(f, dta_d2_wide, nclass = 4, graphs = FALSE, maxiter = 10000)
lc5 <- poLCA(f, dta_d2_wide, nclass = 5, graphs = FALSE, maxiter = 10000)

a <- (data.frame(lc5$probs))
a$Class <- c("Class1", "Class2", "Class3", "Class4", "Class5")

a_long <- a %>% 
  gather(Hour, Prob, -Class) %>% 
  separate(Hour, into = c("HourN", "Carbo"), sep = "\\.") 

a_long$HourN <- factor(a_long$HourN, levels = c("H0","H1" ,"H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10","H11","H12","H13","H14","H15","H16","H17","H18","H19","H20","H21","H22","H23"))

a_long$Carbo <- factor(a_long$Carbo, levels = c("Low_carb", "Med_carb", "High_carb"))


a_long <- a_long %>% 
  filter(Carbo != "Not_eating")

ggthemr("fresh", layout = "scientific")

ggplot(a_long[a_long$Class == "Class1", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
  geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 1: 11.80%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class2", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 2:  8.50%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))

ggplot(a_long[a_long$Class == "Class3", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 3:  25.0%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))



ggplot(a_long[a_long$Class == "Class4", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) + 
 geom_point(size = 3) + 
  geom_line(size = 1.5) + 
  theme(axis.title = element_text(size = 18), 
        axis.text = element_text(size = 18), 
        axis.line = element_line(colour = "black"), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.text = element_text(size = 15), 
        legend.title = element_text(size = 15) 
        # legend.position = "bottom", 
        # legend.direction = "horizontal"
        ) + 
  labs(title = "Class 4:  44.40%", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") + 
  scale_color_discrete(labels = c("Low", "Medium", "High")) + 
  ylim(c(0,1))


ggplot(a_long[a_long$Class == "Class5", ], aes(y = Prob, x=HourN, group = Carbo, color = Carbo)) +
 geom_point(size = 3) +
  geom_line(size = 1.5) +
  theme(axis.title = element_text(size = 18),
        axis.text = element_text(size = 18),
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15)
        # legend.position = "bottom",
        # legend.direction = "horizontal"
        ) +
  labs(title = "Class 5:  %", x = "Hour of the day", y = "Probability",
       color = "Carbohydrate\nintake") +
  scale_color_discrete(labels = c("Low", "Medium", "High")) +
  ylim(c(0,1))
```

